---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-sts
  namespace: {{ .Release.Name }}
  labels: 
    {{- include "unchained.statefulsetLabels" . | nindent 4 }}
spec:
  serviceName: {{ .Chart.Name }}-svc
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:   
      {{- include "unchained.statefulsetLabels" . | nindent 6 }}
  podManagementPolicy: 'Parallel'
  updateStrategy:
    type: 'RollingUpdate'
  template:
    metadata:
      namespace: {{ .Release.Name }}
      labels:
        {{- include "unchained.statefulsetLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 600
      containers: 
        {{- range .Values.statefulset.containers }}
      - name: {{ .name }}
        image: {{ .image }}
        {{- with .env }}
        env: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .ports }}
        ports: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- with .limits }}
          limits:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .requests }}
          requests:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        command: 
          - '/init.sh' 
        startupProbe:
          failureThreshold: 60
          periodSeconds: 30
          timeoutSeconds: 10 
          exec:
            command: 
            - '/startup.sh'
        livenessProbe:
          failureThreshold: 5
          periodSeconds: 30
          timeoutSeconds: 10
          exec:
            command: 
            - '/liveness.sh'
        readinessProbe:
          failureThreshold: 10
          periodSeconds: 30
          timeoutSeconds: 10
          exec:
            command: 
            - '/readiness.sh'
        volumeMounts:
        - name: {{ $.Chart.Name }}-{{ .name }}-data
          mountPath: {{ default "/data" .dataDir }}
        - name: {{ $.Values.name }}
          mountPath: '/init.sh'
          subPath: init.sh
        - name: {{ $.Values.name }}
          mountPath: '/startup.sh'
          subPath: startup.sh
        - name: {{ $.Values.name }}
          mountPath: '/liveness.sh'
          subPath: liveness.sh
        - name: {{ $.Values.name }}
          mountPath: '/readiness.sh'
          subPath: readiness.sh
        - name: {{ $.Values.name }}
          mountPath: '/tendermint.sh'
          subPath: 'tendermint.sh'
      {{- end }}
      volumes: 
        - name: {{ .Values.name }}
          configMap:
            name: {{ .Chart.Name }}-scripts
            defaultMode: 0775
  volumeClaimTemplates:
  {{- range .Values.statefulset.containers }}
  - metadata:
      name: {{ $.Chart.Name }}-{{ .name }}-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ $.Values.global.storageClassName }}
      resources:
        requests:
          storage: {{ .storage_size }}
  {{- end }}